###
GET {{host}}/dwell_time/*/rank
?from_date={{from_date}}
&to_date={{to_date}}
# content-type: application/json
Authorization: Bearer {{jwt}}

###
GET {{host}}/dwell_time/*/count
?app_id_list={{app_id_list}}
&from_date={{from_date}}
&to_date={{to_date}}
&version_list=3.5.8,3.4.8,3.5.2,3.5.3,3.5.1,3.5.4,3.4.7,3.6.1,3.5.5
&duration=day
# content-type: application/json
Authorization: Bearer {{jwt}}