###
POST https://oauth2.googleapis.com/token
content-type: application/x-www-form-urlencoded
# Authorization: Bearer {{jwt}}

assertion=eyJraWQiOiI2ODg4MDA1OGI2NDZlNzk3NWY3MjYyZDQxM2I1ZTk1ZTc1ZjM2YzYxIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzYm5vaEB1c2VyaGFiaXQuaW8iLCJhdWQiOiJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsInNjb3BlIjoiaHR0cHM6Ly9tYWlsLmdvb2dsZS5jb20vIGh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL2F1dGgvZ21haWwuYWRkb25zLmN1cnJlbnQuYWN0aW9uLmNvbXBvc2UgaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vYXV0aC9nbWFpbC5jb21wb3NlIGh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL2F1dGgvZ21haWwubW9kaWZ5IGh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL2F1dGgvZ21haWwuc2VuZCIsImlzcyI6ImVtYWlsLTgzMEBhbXBsaWZpZWQtbGFuZC0yODkxMDQuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJleHAiOjE1OTk4MTI3MjksImlhdCI6MTU5OTgwOTEyOX0.Z0Zbi0PdtpubBwLHkOZtTOVrM-tbUvAj5RHiOpqQFUvCpxKOf4jUq_v0CJahwAmCyCTnw4xEblVwrdyc6cIVRnp-M0rE5NHUc6_4g1b5KtJ6qlgviI1jSbmsTTe-k0ziD8wSY9AGDWfpauwNsyyimsdC1703MXRhLX8BH5y1bmvPriDCKIHUg7nd_OWCDaTkv8ElND44DDnk5l6DRHCjse7SzEEaccw96dyUh_Mm0ilq6swAFFbd4DwOuImw7j2fOL8xLmYPfzMrcgw8mzWTfrEF9IwQjKo02T0LFDHzrGifO2slVxudBQDwtNBRdhgTBM6HHFVpxdgw1V5HNXSGaQ
&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer

###
POST https://content-gmail.googleapis.com/gmail/v1/users/me/messages/send
content-type: text/plain
Authorization: Bearer ya29.a0AfH6SMA7pPi-xlaYqZgHsel0fKUdItq0Kttbf6Bd0oIzZM6INPTQU3y--uBorjlktptvVnMirtUE3rJTH-PhYOS-UKN7G6o5A7jVjG68WLUDa5wI7FDS5wtBzRkAuSptXM6oBbUAbLY-XtqzhRlEIYI8TSC8nz_39oJZ8rLaH2yAQNnP4ni9d_inZJ86u06LA_EmnnWpoZXuzlj8ac0jbKazG18

{
  "raw": "Q29udGVudC1UeXBlOiB0ZXh0L2h0bWw7IGNoYXJzZXQ9IlVURi04IgpGcm9tOiBoZWxwZXIgPHNibm9oQHVzaGVyaGFiaXQuaW8+ClRvOiBzYm5vaCA8c2Jub2hAdXNlcmhhYml0LmlvPgpTdWJqZWN0OiB0ZXN0IHN1YmplY3QKCnRlc3QgY29udGVudA=="
}