### GET request with a header
GET http://localhost:8080/api
Accept: application/json

### Send POST request with json body
POST http://localhost:8080/api
Content-Type: application/json

{
  "email": "youngjo@dong-a.com",
  "password": "1234",
  "name": "youngjo"
}

###
PUT http://localhost:8080/api
Content-Type: application/json

{
  "email": "test@dong-a.com",
  "password": "1234",
  "name": "Kong"
}

###
DELETE http://localhost:8080/api/1
Accept: application/json

