spring:
  profiles:
    group:
      "test": "testdb,common"
      "dev":  "testdb,common"
      "prod": "proddb,common"

---
spring:
  datasource:
    url: "r2dbc:h2:mem://localhost/testdb;MODE=MYSQL;DATABASE_TO_LOWER=true;DATABASE_TO_UPPER=false"
    username: "sa"
    password:
  config:
    activate:
      on-profile: "testdb"

---
spring:
  datasource:
    url: "r2dbc:pool:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf8"
    username: "root"
    password: "devpassword"
  config:
    activate:
      on-profile: "proddb"

---
spring:
  config:
    activate:
      on-profile: "common"

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8