spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  profiles:
    active: dev
    include:
  #      - core
#      - domain
#      - adapter

  servlet:
    multipart:
      max-file-size: 10MB

#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:~/testdb;AUTO_SERVER=TRUE;MODE=MySQL
#    username: sa
#    password:

  datasource:
    url: "jdbc:mysql://db-2i72s-kr1.vpc-pub-cdb.gov-ntruss.com:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul"
    username: test
    password: 12281228a!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true

---
spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  profiles:
    active: local
    include:
  #      - core
#      - domain
#      - adapter

  servlet:
    multipart:
      max-file-size: 10MB

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/testdb;MODE=MySQL
    username: sa
    password:

#  jpa:
#    database: mysql
#    database-platform: org.h2.Driver
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
#        hbm2ddl:
#          auto: create
#    hibernate:
#      ddl-auto: none
#    open-in-view: false
#    show-sql: true


---
spring:
  config:
    activate:
      on-profile: prod

  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./testdb;MODE=MySQL
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          format_sql: true
          show-sql: true
          generate-ddl: true
          database-platform: org.hibernate.dialect.MySQL8Dialect